"""add user table and job.user_id

Revision ID: 19fe20946664
Revises: d19555eaae72
Create Date: 2026-08-04 07:47:09.921000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fe20946664'
down_revision: Union[str, None] = 'd19555eaae72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
