"""add memory_type to accelerator

Revision ID: 2946e33c128e
Revises: 3b7dbe6c2399
Create Date: 2026-07-20 10:07:42.712720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2946e33c128e'
down_revision: Union[str, None] = '3b7dbe6c2399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accelerator', sa.Column('memory_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accelerator', 'memory_type')
    # ### end Alembic commands ###
