"""add job_training_profile table

Revision ID: 38dd46f34468
Revises: b0c0bcc812ed
Create Date: 2026-07-21 09:36:30.386518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dd46f34468'
down_revision: Union[str, None] = 'b0c0bcc812ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_training_profile',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('start_value', sa.Numeric(), nullable=False),
    sa.Column('target_value', sa.Numeric(), nullable=False),
    sa.Column('curve_shape', sa.String(), nullable=False),
    sa.Column('noise_amplitude', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_training_profile')
    # ### end Alembic commands ###
