"""add job phase_deadline for provisioning/finalizing lifecycle

Revision ID: 435fab2f4368
Revises: e6d10b173bf6
Create Date: 2026-08-17 16:49:14.321965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435fab2f4368'
down_revision: Union[str, None] = 'e6d10b173bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('phase_deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'phase_deadline')
    # ### end Alembic commands ###
