"""add job_cache_profile and cache_prediction_point tables

Revision ID: 440f0cc3a956
Revises: 7d0cd97a62aa
Create Date: 2026-07-22 06:27:59.319151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440f0cc3a956'
down_revision: Union[str, None] = '7d0cd97a62aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_prediction_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predicted', sa.Numeric(), nullable=False),
    sa.Column('actual', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_cache_profile',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('vram_target_pct', sa.Numeric(), nullable=False),
    sa.Column('vram_transfer_gbps', sa.Numeric(), nullable=False),
    sa.Column('dram_target_pct', sa.Numeric(), nullable=False),
    sa.Column('dram_transfer_gbps', sa.Numeric(), nullable=False),
    sa.Column('ssd_target_pct', sa.Numeric(), nullable=False),
    sa.Column('ssd_transfer_gbps', sa.Numeric(), nullable=False),
    sa.Column('hit_rate_target_pct', sa.Numeric(), nullable=False),
    sa.Column('latency_reduction_pct', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_cache_profile')
    op.drop_table('cache_prediction_point')
    # ### end Alembic commands ###
