"""add negotiation_story, negotiation_round, feasible_candidate; FK job.priority_pref

Revision ID: 4c3818bf95c8
Revises: 741a23104f72
Create Date: 2026-07-22 08:12:30.855131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3818bf95c8'
down_revision: Union[str, None] = '741a23104f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_pref', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority_pref')
    )
    op.create_table('negotiation_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('csc_proposal', sa.String(), nullable=False),
    sa.Column('csp_proposal', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['negotiation_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feasible_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negotiation_round_id', sa.Integer(), nullable=False),
    sa.Column('combo_desc', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_round_id'], ['negotiation_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # seed the 3 fixed stories before adding the FK, since existing job rows
    # already use these priority_pref values and would violate the constraint otherwise
    op.execute(
        "INSERT INTO negotiation_story (priority_pref) VALUES ('time'), ('cost'), ('balanced')"
    )
    op.create_foreign_key(None, 'job', 'negotiation_story', ['priority_pref'], ['priority_pref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_table('feasible_candidate')
    op.drop_table('negotiation_round')
    op.drop_table('negotiation_story')
    # ### end Alembic commands ###
