"""add indexes on hot job_id/status/occurred_at columns

Revision ID: 5645725e38b5
Revises: d4b6e91a7c53
Create Date: 2026-08-26 07:29:32.161304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5645725e38b5'
down_revision: Union[str, None] = 'd4b6e91a7c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assignment_job_id'), 'assignment', ['job_id'], unique=False)
    op.create_index(op.f('ix_event_job_id'), 'event', ['job_id'], unique=False)
    op.create_index(op.f('ix_event_occurred_at'), 'event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_hyperparam_adjustment_job_id'), 'hyperparam_adjustment', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_cache_tier_job_id'), 'job_cache_tier', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_metric_profile_job_id'), 'job_metric_profile', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_negotiation_item_job_id'), 'job_negotiation_item', ['job_id'], unique=False)
    op.create_index(op.f('ix_reallocation_donor_job_id'), 'reallocation', ['donor_job_id'], unique=False)
    op.create_index(op.f('ix_reallocation_receiver_job_id'), 'reallocation', ['receiver_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reallocation_receiver_job_id'), table_name='reallocation')
    op.drop_index(op.f('ix_reallocation_donor_job_id'), table_name='reallocation')
    op.drop_index(op.f('ix_job_negotiation_item_job_id'), table_name='job_negotiation_item')
    op.drop_index(op.f('ix_job_metric_profile_job_id'), table_name='job_metric_profile')
    op.drop_index(op.f('ix_job_cache_tier_job_id'), table_name='job_cache_tier')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_hyperparam_adjustment_job_id'), table_name='hyperparam_adjustment')
    op.drop_index(op.f('ix_event_occurred_at'), table_name='event')
    op.drop_index(op.f('ix_event_job_id'), table_name='event')
    op.drop_index(op.f('ix_assignment_job_id'), table_name='assignment')
    # ### end Alembic commands ###
