"""drop event.accelerator_id

Revision ID: 5e09240b84a1
Revises: a03f8dbf8655
Create Date: 2026-07-27 06:03:33.228047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e09240b84a1'
down_revision: Union[str, None] = 'a03f8dbf8655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_accelerator_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'accelerator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('accelerator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_accelerator_id_fkey', 'event', 'accelerator', ['accelerator_id'], ['id'])
    # ### end Alembic commands ###
