"""add model_name to resource_tier_requirement

Revision ID: 61025beb54ba
Revises: 19fe20946664
Create Date: 2026-08-05 08:58:24.640275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61025beb54ba'
down_revision: Union[str, None] = '19fe20946664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_tier_requirement', sa.Column('model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_tier_requirement', 'model_name')
    # ### end Alembic commands ###
