"""add reallocation table and FK on event.reallocation_id

Revision ID: 741a23104f72
Revises: 04d8d22394f7
Create Date: 2026-07-22 07:56:54.472538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741a23104f72'
down_revision: Union[str, None] = '04d8d22394f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reallocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_job_id', sa.Integer(), nullable=False),
    sa.Column('receiver_job_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('at_t_offset_sec', sa.Integer(), nullable=False),
    sa.Column('delta_u_gain', sa.Numeric(), nullable=False),
    sa.Column('delta_u_loss', sa.Numeric(), nullable=False),
    sa.Column('downtime_sec', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['donor_job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['receiver_job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'event', 'reallocation', ['reallocation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_table('reallocation')
    # ### end Alembic commands ###
