"""add node_id to event

Revision ID: 7c2aeac8d91f
Revises: 38dd46f34468
Create Date: 2026-07-22 01:23:44.743320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2aeac8d91f'
down_revision: Union[str, None] = '38dd46f34468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('node_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'node', ['node_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'node_id')
    # ### end Alembic commands ###
