"""add profiling flag to job_metric_profile

Revision ID: 7c94e9a54cf4
Revises: 435fab2f4368
Create Date: 2026-08-20 04:34:24.657385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c94e9a54cf4'
down_revision: Union[str, None] = '435fab2f4368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_metric_profile', sa.Column('profiling', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_metric_profile', 'profiling')
    # ### end Alembic commands ###
