"""add model_layer and model_layer_edge tables

Revision ID: 7d0cd97a62aa
Revises: 7c2aeac8d91f
Create Date: 2026-07-22 02:16:26.469091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0cd97a62aa'
down_revision: Union[str, None] = '7c2aeac8d91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('op_name', sa.String(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('gflops', sa.Numeric(), nullable=False),
    sa.Column('mem_mb', sa.Numeric(), nullable=False),
    sa.Column('characteristic', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_layer_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_layer_id', sa.Integer(), nullable=False),
    sa.Column('to_layer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_layer_id'], ['model_layer.id'], ),
    sa.ForeignKeyConstraint(['to_layer_id'], ['model_layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_layer_edge')
    op.drop_table('model_layer')
    # ### end Alembic commands ###
