"""add hyperparam_adjustment table

Revision ID: 85064cce862f
Revises: 440f0cc3a956
Create Date: 2026-07-22 06:57:43.685877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85064cce862f'
down_revision: Union[str, None] = '440f0cc3a956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hyperparam_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_offset_sec', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Numeric(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('data_shard', sa.Integer(), nullable=False),
    sa.Column('workers', sa.Integer(), nullable=False),
    sa.Column('lr_multiplier', sa.Numeric(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hyperparam_adjustment')
    # ### end Alembic commands ###
