"""prototype v2 rework: fed links, node alerts, generic job metrics, simplified negotiation/cache/kqv/dart/reallocation

Revision ID: a03f8dbf8655
Revises: 4c3818bf95c8
Create Date: 2026-07-27 05:42:36.021371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03f8dbf8655'
down_revision: Union[str, None] = '4c3818bf95c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cache_tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('fill_pct', sa.Numeric(), nullable=False),
    sa.Column('latency_ms', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_kqv_benchmark',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kqv_gain_pct', sa.Numeric(), nullable=True),
    sa.Column('kqv_even_makespan_sec', sa.Numeric(), nullable=True),
    sa.Column('kqv_opt_makespan_sec', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_metric_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('start_value', sa.Numeric(), nullable=True),
    sa.Column('target_value', sa.Numeric(), nullable=True),
    sa.Column('curve_shape', sa.String(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_negotiation',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('agreement_pct', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_negotiation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_federation_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_a_id', sa.Integer(), nullable=False),
    sa.Column('cluster_b_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_a_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['cluster_b_id'], ['cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('job_priority_pref_fkey', 'job', type_='foreignkey')
    op.drop_table('feasible_candidate')
    op.drop_table('negotiation_round')
    op.drop_table('negotiation_story')
    op.drop_table('cache_prediction_point')
    op.drop_table('job_training_profile')
    op.drop_table('kqv_allocation')
    op.drop_table('job_benchmark')
    op.add_column('hyperparam_adjustment', sa.Column('param_name', sa.String(), nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('from_value', sa.String(), nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('to_value', sa.String(), nullable=False))
    op.alter_column('hyperparam_adjustment', 'reward',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('hyperparam_adjustment', 'batch_size')
    op.drop_column('hyperparam_adjustment', 'action')
    op.drop_column('hyperparam_adjustment', 'data_shard')
    op.drop_column('hyperparam_adjustment', 'workers')
    op.drop_column('hyperparam_adjustment', 'lr_multiplier')
    op.drop_column('job_cache_profile', 'ssd_target_pct')
    op.drop_column('job_cache_profile', 'dram_target_pct')
    op.drop_column('job_cache_profile', 'ssd_transfer_gbps')
    op.drop_column('job_cache_profile', 'dram_transfer_gbps')
    op.drop_column('job_cache_profile', 'vram_transfer_gbps')
    op.drop_column('job_cache_profile', 'hit_rate_target_pct')
    op.drop_column('job_cache_profile', 'vram_target_pct')
    op.add_column('reallocation', sa.Column('resume_delay_sec', sa.Numeric(), nullable=False))
    op.drop_column('reallocation', 'delta_u_gain')
    op.drop_column('reallocation', 'delta_u_loss')
    op.add_column('region', sa.Column('latitude', sa.Numeric(), nullable=False))
    op.add_column('region', sa.Column('longitude', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'longitude')
    op.drop_column('region', 'latitude')
    op.add_column('reallocation', sa.Column('delta_u_loss', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('reallocation', sa.Column('delta_u_gain', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('reallocation', 'resume_delay_sec')
    op.add_column('job_cache_profile', sa.Column('vram_target_pct', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('job_cache_profile', sa.Column('hit_rate_target_pct', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('job_cache_profile', sa.Column('vram_transfer_gbps', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('job_cache_profile', sa.Column('dram_transfer_gbps', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('job_cache_profile', sa.Column('ssd_transfer_gbps', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('job_cache_profile', sa.Column('dram_target_pct', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('job_cache_profile', sa.Column('ssd_target_pct', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('lr_multiplier', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('workers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('data_shard', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hyperparam_adjustment', sa.Column('batch_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('hyperparam_adjustment', 'reward',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('hyperparam_adjustment', 'to_value')
    op.drop_column('hyperparam_adjustment', 'from_value')
    op.drop_column('hyperparam_adjustment', 'param_name')
    op.create_table('job_benchmark',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kqv_gain_pct', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('kqv_even_makespan_sec', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('kqv_opt_makespan_sec', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='job_benchmark_job_id_fkey'),
    sa.PrimaryKeyConstraint('job_id', name='job_benchmark_pkey')
    )
    op.create_table('kqv_allocation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('even_shard', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('optimized_shard', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='kqv_allocation_job_id_fkey'),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name='kqv_allocation_node_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='kqv_allocation_pkey')
    )
    op.create_table('feasible_candidate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('negotiation_round_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('combo_desc', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['negotiation_round_id'], ['negotiation_round.id'], name='feasible_candidate_negotiation_round_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feasible_candidate_pkey')
    )
    op.create_table('job_training_profile',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('curve_shape', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('noise_amplitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='job_training_profile_job_id_fkey'),
    sa.PrimaryKeyConstraint('job_id', name='job_training_profile_pkey')
    )
    op.create_table('cache_prediction_point',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('predicted', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('actual', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cache_prediction_point_pkey')
    )
    op.create_table('negotiation_round',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('round_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('csc_proposal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('csp_proposal', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['negotiation_story.id'], name='negotiation_round_story_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='negotiation_round_pkey')
    )
    op.create_table('negotiation_story',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('priority_pref', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='negotiation_story_pkey'),
    sa.UniqueConstraint('priority_pref', name='negotiation_story_priority_pref_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_foreign_key('job_priority_pref_fkey', 'job', 'negotiation_story', ['priority_pref'], ['priority_pref'])
    op.drop_table('node_alert')
    op.drop_table('cluster_federation_link')
    op.drop_table('job_negotiation_item')
    op.drop_table('job_negotiation')
    op.drop_table('job_metric_profile')
    op.drop_table('job_kqv_benchmark')
    op.drop_table('job_cache_tier')
    # ### end Alembic commands ###
