"""assignment scheduled by node, not accelerator

Revision ID: b0c0bcc812ed
Revises: 0245de56f68b
Create Date: 2026-07-21 07:36:03.287295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c0bcc812ed'
down_revision: Union[str, None] = '0245de56f68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accelerator', 'total_capacity')
    op.add_column('assignment', sa.Column('node_id', sa.Integer(), nullable=False))
    op.drop_constraint('assignment_accelerator_id_fkey', 'assignment', type_='foreignkey')
    op.create_foreign_key(None, 'assignment', 'node', ['node_id'], ['id'])
    op.drop_column('assignment', 'allocated_capacity')
    op.drop_column('assignment', 'accelerator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('accelerator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assignment', sa.Column('allocated_capacity', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.create_foreign_key('assignment_accelerator_id_fkey', 'assignment', 'accelerator', ['accelerator_id'], ['id'])
    op.drop_column('assignment', 'node_id')
    op.add_column('accelerator', sa.Column('total_capacity', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
