"""add node.purpose

Revision ID: d19555eaae72
Revises: 5fcc49cbc30e
Create Date: 2026-08-04 06:48:00.253295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19555eaae72'
down_revision: Union[str, None] = '5fcc49cbc30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('purpose', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'purpose')
    # ### end Alembic commands ###
