"""add model_memory_profile table

Revision ID: d4b6e91a7c53
Revises: 7c94e9a54cf4
Create Date: 2026-08-25 09:12:04.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b6e91a7c53'
down_revision: Union[str, None] = '7c94e9a54cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_memory_profile',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('peak_mb', sa.Numeric(), nullable=False),
    sa.Column('trough_mb', sa.Numeric(), nullable=False),
    sa.Column('reserved_mb', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_memory_profile')
    # ### end Alembic commands ###
