"""add partial unique index for one active assignment per node

Revision ID: d8b9ec7d9bad
Revises: e73f0f73c725
Create Date: 2026-08-07 05:27:13.252781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b9ec7d9bad'
down_revision: Union[str, None] = 'e73f0f73c725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assignment_active_node', 'assignment', ['node_id'], unique=True, postgresql_where=sa.text('to_t IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_active_node', table_name='assignment', postgresql_where=sa.text('to_t IS NULL'))
    # ### end Alembic commands ###
