"""add job duration_sec override for filler jobs

Revision ID: e6d10b173bf6
Revises: d8b9ec7d9bad
Create Date: 2026-08-07 07:37:17.748185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d10b173bf6'
down_revision: Union[str, None] = 'd8b9ec7d9bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('duration_sec', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'duration_sec')
    # ### end Alembic commands ###
