"""add accelerator_model table, reference by id instead of model_name string

Revision ID: e73f0f73c725
Revises: 61025beb54ba
Create Date: 2026-08-05 10:10:21.841211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73f0f73c725'
down_revision: Union[str, None] = '61025beb54ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accelerator_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accelerator', sa.Column('accelerator_model_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accelerator', 'accelerator_model', ['accelerator_model_id'], ['id'])
    op.drop_column('accelerator', 'model_name')
    op.add_column('resource_tier_requirement', sa.Column('accelerator_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource_tier_requirement', 'accelerator_model', ['accelerator_model_id'], ['id'])
    op.drop_column('resource_tier_requirement', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_tier_requirement', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resource_tier_requirement', type_='foreignkey')
    op.drop_column('resource_tier_requirement', 'accelerator_model_id')
    op.add_column('accelerator', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accelerator', type_='foreignkey')
    op.drop_column('accelerator', 'accelerator_model_id')
    op.drop_table('accelerator_model')
    # ### end Alembic commands ###
